### ISSUE TITLE
Add `.devcontainer` with required local dev tools

### ISSUE THREAD

**Issue by mathieu-benoit** [score-spec/sample-score-app#12]
It would be great to have the support of `.devcontainer` with required local dev tools (`score-compose` and `score-helm` - in addition to `kubectl`, `docker`, `kind`, `curl`) already installed/prepared.

Very convenient for local setup, in Codespace, with VS Code:
- https://code.visualstudio.com/docs/devcontainers/create-dev-container
- https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers

**Comment by sujaya-sys** [comment]
@mathieu-benoit Could you provide a little more context on this issue? Thank you!

**Comment by mathieu-benoit** [comment]
@sujaya-sys, sure thing, I updated the description to be more precise. It's not just for this sample apps, it could be helpful for any repo dealing with `score-compose` and `score-helm`.

**Comment by mathieu-benoit** [comment]
Proposing this: https://github.com/score-spec/sample-score-app/pull/22.
